//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GreatDBBackupRecord) DeepCopyInto(out *GreatDBBackupRecord) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GreatDBBackupRecord.
func (in *GreatDBBackupRecord) DeepCopy() *GreatDBBackupRecord {
	if in == nil {
		return nil
	}
	out := new(GreatDBBackupRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GreatDBBackupRecord) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GreatDBBackupRecordList) DeepCopyInto(out *GreatDBBackupRecordList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GreatDBBackupRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GreatDBBackupRecordList.
func (in *GreatDBBackupRecordList) DeepCopy() *GreatDBBackupRecordList {
	if in == nil {
		return nil
	}
	out := new(GreatDBBackupRecordList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GreatDBBackupRecordList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GreatDBBackupRecordSpec) DeepCopyInto(out *GreatDBBackupRecordSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GreatDBBackupRecordSpec.
func (in *GreatDBBackupRecordSpec) DeepCopy() *GreatDBBackupRecordSpec {
	if in == nil {
		return nil
	}
	out := new(GreatDBBackupRecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GreatDBBackupRecordStatus) DeepCopyInto(out *GreatDBBackupRecordStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GreatDBBackupRecordStatus.
func (in *GreatDBBackupRecordStatus) DeepCopy() *GreatDBBackupRecordStatus {
	if in == nil {
		return nil
	}
	out := new(GreatDBBackupRecordStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GreatDBBackupSchedule) DeepCopyInto(out *GreatDBBackupSchedule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GreatDBBackupSchedule.
func (in *GreatDBBackupSchedule) DeepCopy() *GreatDBBackupSchedule {
	if in == nil {
		return nil
	}
	out := new(GreatDBBackupSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GreatDBBackupSchedule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GreatDBBackupScheduleList) DeepCopyInto(out *GreatDBBackupScheduleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GreatDBBackupSchedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GreatDBBackupScheduleList.
func (in *GreatDBBackupScheduleList) DeepCopy() *GreatDBBackupScheduleList {
	if in == nil {
		return nil
	}
	out := new(GreatDBBackupScheduleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GreatDBBackupScheduleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GreatDBBackupScheduleSpec) DeepCopyInto(out *GreatDBBackupScheduleSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GreatDBBackupScheduleSpec.
func (in *GreatDBBackupScheduleSpec) DeepCopy() *GreatDBBackupScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(GreatDBBackupScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GreatDBBackupScheduleStatus) DeepCopyInto(out *GreatDBBackupScheduleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GreatDBBackupScheduleStatus.
func (in *GreatDBBackupScheduleStatus) DeepCopy() *GreatDBBackupScheduleStatus {
	if in == nil {
		return nil
	}
	out := new(GreatDBBackupScheduleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GreatDBPaxos) DeepCopyInto(out *GreatDBPaxos) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GreatDBPaxos.
func (in *GreatDBPaxos) DeepCopy() *GreatDBPaxos {
	if in == nil {
		return nil
	}
	out := new(GreatDBPaxos)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GreatDBPaxos) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GreatDBPaxosList) DeepCopyInto(out *GreatDBPaxosList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GreatDBPaxos, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GreatDBPaxosList.
func (in *GreatDBPaxosList) DeepCopy() *GreatDBPaxosList {
	if in == nil {
		return nil
	}
	out := new(GreatDBPaxosList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GreatDBPaxosList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GreatDBPaxosSpec) DeepCopyInto(out *GreatDBPaxosSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GreatDBPaxosSpec.
func (in *GreatDBPaxosSpec) DeepCopy() *GreatDBPaxosSpec {
	if in == nil {
		return nil
	}
	out := new(GreatDBPaxosSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GreatDBPaxosStatus) DeepCopyInto(out *GreatDBPaxosStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GreatDBPaxosStatus.
func (in *GreatDBPaxosStatus) DeepCopy() *GreatDBPaxosStatus {
	if in == nil {
		return nil
	}
	out := new(GreatDBPaxosStatus)
	in.DeepCopyInto(out)
	return out
}
