---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-greatdb-greatdb-com-v1-greatdbbackuprecord
  failurePolicy: Fail
  name: mgreatdbbackuprecord-v1.kb.io
  rules:
  - apiGroups:
    - greatdb.greatdb.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - greatdbbackuprecords
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-greatdb-greatdb-com-v1-greatdbbackupschedule
  failurePolicy: Fail
  name: mgreatdbbackupschedule-v1.kb.io
  rules:
  - apiGroups:
    - greatdb.greatdb.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - greatdbbackupschedules
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-greatdb-greatdb-com-v1-greatdbpaxos
  failurePolicy: Fail
  name: mgreatdbpaxos-v1.kb.io
  rules:
  - apiGroups:
    - greatdb.greatdb.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - greatdbpaxos
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-greatdb-greatdb-com-v1-greatdbbackuprecord
  failurePolicy: Fail
  name: vgreatdbbackuprecord-v1.kb.io
  rules:
  - apiGroups:
    - greatdb.greatdb.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - greatdbbackuprecords
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-greatdb-greatdb-com-v1-greatdbbackupschedule
  failurePolicy: Fail
  name: vgreatdbbackupschedule-v1.kb.io
  rules:
  - apiGroups:
    - greatdb.greatdb.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - greatdbbackupschedules
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-greatdb-greatdb-com-v1-greatdbpaxos
  failurePolicy: Fail
  name: vgreatdbpaxos-v1.kb.io
  rules:
  - apiGroups:
    - greatdb.greatdb.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - greatdbpaxos
  sideEffects: None
