---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - greatdb.greatdb.com
  resources:
  - greatdbbackuprecords
  - greatdbbackupschedules
  - greatdbpaxos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - greatdb.greatdb.com
  resources:
  - greatdbbackuprecords/finalizers
  - greatdbbackupschedules/finalizers
  - greatdbpaxos/finalizers
  verbs:
  - update
- apiGroups:
  - greatdb.greatdb.com
  resources:
  - greatdbbackuprecords/status
  - greatdbbackupschedules/status
  - greatdbpaxos/status
  verbs:
  - get
  - patch
  - update
