package configmap

const (
	CreateDbscaleConfigMapFailedReason = "failed to create router configmap"
	CreateGreatdbConfigMapFailedReason = "failed to create greatdb configmap"
	SyncDBscaleConfigmapFailedReason   = "failed to sync router configmap"
	SyncGreatDbConfigmapFailedReason   = "failed to sync greatdb configmap"
)

const (
	greatdbConfigTemplate = `
[client]
socket    = /greatdb/mysql/socket/mysql.sock

[mysqld]
datadir = /greatdb/mysql/data/
port = 3306
socket = /greatdb/mysql/socket/mysql.sock
mysqlx = 0
mysqlx_port = 33060
mysqlx_socket = /greatdb/mysql/socket/mysqlx.sock
user = greatdb
report_host = REPORTHOST
admin_address = 127.0.0.1
admin_port = 33062
server_id = SERVERID
tmpdir = /greatdb/mysql/tmp/
general_log_file = /greatdb/mysql/logfile/general.log
log_bin = /greatdb/mysql/logfile/binlog
relay_log = /greatdb/mysql/logfile/relaylog
slow_query_log_file = /greatdb/mysql/logfile/slow.log
log_error = /greatdb/mysql/logfile/error.log
pid_file = /greatdb/mysql/pid/mysqld.pid

back_log = 5000
binlog_format = row
binlog_ignore_db = dbscale_tmp
binlog_transaction_dependency_tracking = WRITESET
character_set_server = utf8
default_authentication_plugin = mysql_native_password
enforce_gtid_consistency = on
expire_logs_days = 15
federated = 1
gtid_mode = on
init_connect = SET NAMES utf8
innodb_buffer_pool_instances = 10
innodb_buffer_pool_size = 1G
innodb_change_buffering = all
innodb_doublewrite = 1
innodb_file_per_table = 1
innodb_flush_log_at_trx_commit = 1
innodb_flush_method = O_DIRECT
innodb_io_capacity = 8000
innodb_io_capacity_max = 10000
innodb_log_buffer_size = 128M
innodb_log_files_in_group = 4
innodb_log_file_size = 1G
innodb_monitor_enable = all
innodb_print_all_deadlocks = on
innodb_read_io_threads = 4
innodb_temp_data_file_path = ibtmp1:12M:autoextend:max:81920M
innodb_thread_concurrency = 0
innodb_write_io_threads = 4
interactive_timeout = 31536000
log_bin_trust_function_creators = 1
log_slave_updates = 1
log_timestamps = SYSTEM
long_query_time = 10
lower_case_table_names = 1
master_info_repository = TABLE
max_allowed_packet = 16M
max_connections = 4000
max_prepared_stmt_count = 1048576
net_read_timeout = 10000
net_write_timeout = 10000
open_files_limit = 800000
performance-schema-consumer-events_stages_current = on
performance-schema-consumer-events_stages_history = on
performance-schema-consumer-events_statements_current = on
performance-schema-consumer-events_statements_history = on
performance-schema-consumer-events_transactions_current = on
performance-schema-consumer-events_transactions_history = on
performance-schema-consumer-events_waits_current = on
performance-schema-consumer-events_waits_history = on
performance-schema-instrument = %=ON
relay_log_info_repository = TABLE
skip_external_locking = 1

skip_slave_start = 1
relay_log_recovery = 1
slave_parallel_type = LOGICAL_CLOCK
slave_parallel_workers = 16
slave_pending_jobs_size_max = 2147483648
slave_preserve_commit_order = 1
slave_rows_search_algorithms = INDEX_SCAN,HASH_SCAN
slow_query_log = on
sort_buffer_size = 2M
tls-version=""
sync_binlog = 1
table_definition_cache = 5000
table_open_cache = 5000
thread_cache_size = 3000
transaction_isolation = READ-COMMITTED
transaction_write_set_extraction = XXHASH64
wait_timeout = 31536000



loose-plugin_load_add = 'mysql_clone.so'
loose-plugin_load_add = 'group_replication.so'
loose-group_replication_group_name = "9a84d4d4-4fd4-43fd-804b-b94a112d74a9"

loose-group_replication_ip_whitelist = '0.0.0.0/0'
loose-group_replication_local_address = "GROUPLOCALADDRESS"
loose-group_replication_group_seeds = ''

loose-group_replication_start_on_boot = OFF
loose-group_replication_bootstrap_group = OFF
loose-group_replication_exit_state_action = READ_ONLY
loose-group_replication_flow_control_mode = "DISABLED"
loose-group_replication_single_primary_mode = ON
loose-group_replication_majority_after_mode = ON
loose-group_replication_communication_max_message_size = 10M
loose-group_replication_arbitrator = 0
loose-group_replication_single_primary_fast_mode = 1
loose-group_replication_request_time_threshold = 100
loose-group_replication_primary_election_mode = GTID_FIRST
loose-group_replication_unreachable_majority_timeout = 30
loose-group_replication_member_expel_timeout = 5
loose-group_replication_autorejoin_tries = 288

`
)

var GreatdbFixedOptions = map[string]bool{
	"datadir":                              true,
	"port":                                 true,
	"socket":                               true,
	"mysqlx":                               true,
	"mysqlx_port":                          true,
	"mysqlx_socket":                        true,
	"user":                                 true,
	"report_host":                          true,
	"admin_address":                        true,
	"admin_port":                           true,
	"server_id":                            true,
	"tmpdir":                               true,
	"general_log_file":                     true,
	"log_bin":                              true,
	"relay_log":                            true,
	"slow_query_log_file":                  true,
	"log_error":                            true,
	"pid_file":                             true,
	"loose-group_replication_group_seeds":  true,
	"loose-group_replication_ip_whitelist": true,
	"oose-group_replication_local_address": true,
}

// https://dev.mysql.com/doc/refman/8.0/en/dynamic-system-variables.html
var GreatdbSupportDynamicOptions = map[string]string{
	"activate_all_roles_on_login":                           "bool",
	"admin_ssl_ca":                                          "string",
	"admin_ssl_capath":                                      "string",
	"admin_ssl_cert":                                        "string",
	"admin_ssl_cipher":                                      "string",
	"admin_ssl_crl":                                         "string",
	"admin_ssl_crlpath":                                     "string",
	"admin_ssl_key":                                         "string",
	"admin_tls_ciphersuites":                                "string",
	"admin_tls_version":                                     "string",
	"audit_log_connection_policy":                           "str",
	"audit_log_disable":                                     "bool",
	"audit_log_exclude_accounts":                            "string",
	"audit_log_flush":                                       "bool",
	"audit_log_format_unix_timestamp":                       "bool",
	"audit_log_include_accounts":                            "string",
	"audit_log_max_size":                                    "int",
	"audit_log_password_history_keep_days":                  "int",
	"audit_log_prune_seconds":                               "int",
	"audit_log_read_buffer_size":                            "int",
	"audit_log_rotate_on_size":                              "int",
	"audit_log_statement_policy":                            "str",
	"authentication_fido_rp_id":                             "string",
	"authentication_kerberos_service_principal":             "string",
	"authentication_ldap_sasl_auth_method_name":             "string",
	"authentication_ldap_sasl_bind_base_dn":                 "string",
	"authentication_ldap_sasl_bind_root_dn":                 "string",
	"authentication_ldap_sasl_bind_root_pwd":                "string",
	"authentication_ldap_sasl_ca_path":                      "string",
	"authentication_ldap_sasl_group_search_attr":            "string",
	"authentication_ldap_sasl_group_search_filter":          "string",
	"authentication_ldap_sasl_init_pool_size":               "int",
	"authentication_ldap_sasl_log_status":                   "int",
	"authentication_ldap_sasl_max_pool_size":                "int",
	"authentication_ldap_sasl_referral":                     "bool",
	"authentication_ldap_sasl_server_host":                  "string",
	"authentication_ldap_sasl_server_port":                  "int",
	"authentication_ldap_sasl_tls":                          "bool",
	"authentication_ldap_sasl_user_search_attr":             "string",
	"authentication_ldap_simple_auth_method_name":           "string",
	"authentication_ldap_simple_bind_base_dn":               "string",
	"authentication_ldap_simple_bind_root_dn":               "string",
	"authentication_ldap_simple_bind_root_pwd":              "string",
	"authentication_ldap_simple_ca_path":                    "string",
	"authentication_ldap_simple_group_search_attr":          "string",
	"authentication_ldap_simple_group_search_filter":        "string",
	"authentication_ldap_simple_init_pool_size":             "int",
	"authentication_ldap_simple_log_status":                 "int",
	"authentication_ldap_simple_max_pool_size":              "int",
	"authentication_ldap_simple_referral":                   "bool",
	"authentication_ldap_simple_server_host":                "string",
	"authentication_ldap_simple_server_port":                "int",
	"authentication_ldap_simple_tls":                        "bool",
	"authentication_ldap_simple_user_search_attr":           "string",
	"authentication_policy":                                 "string",
	"auto_increment_increment":                              "int",
	"auto_increment_offset":                                 "int",
	"autocommit":                                            "bool",
	"automatic_sp_privileges":                               "bool",
	"avoid_temporal_upgrade":                                "bool",
	"big_tables":                                            "bool",
	"binlog_cache_size":                                     "int",
	"binlog_checksum":                                       "string",
	"binlog_direct_non_transactional_updates":               "bool",
	"binlog_encryption":                                     "bool",
	"binlog_error_action":                                   "str",
	"binlog_expire_logs_auto_purge":                         "bool",
	"binlog_expire_logs_seconds":                            "int",
	"binlog_format":                                         "str",
	"binlog_group_commit_sync_delay":                        "int",
	"binlog_group_commit_sync_no_delay_count":               "int",
	"binlog_max_flush_queue_time":                           "int",
	"binlog_order_commits":                                  "bool",
	"binlog_row_image":                                      "str",
	"binlog_row_metadata":                                   "str",
	"binlog_row_value_options":                              "Set",
	"binlog_rows_query_log_events":                          "bool",
	"binlog_stmt_cache_size":                                "int",
	"binlog_transaction_compression":                        "bool",
	"binlog_transaction_compression_level_zstd":             "int",
	"binlog_transaction_dependency_history_size":            "int",
	"binlog_transaction_dependency_tracking":                "str",
	"block_encryption_mode":                                 "string",
	"bulk_insert_buffer_size":                               "int",
	"character_set_client":                                  "string",
	"character_set_connection":                              "string",
	"character_set_database":                                "string",
	"character_set_filesystem":                              "string",
	"character_set_results":                                 "string",
	"character_set_server":                                  "string",
	"check_proxy_users":                                     "bool",
	"clone_autotune_concurrency":                            "bool",
	"clone_block_ddl":                                       "bool",
	"clone_buffer_size":                                     "int",
	"clone_ddl_timeout":                                     "int",
	"clone_delay_after_data_drop":                           "int",
	"clone_donor_timeout_after_network_failure":             "int",
	"clone_enable_compression":                              "bool",
	"clone_max_concurrency":                                 "int",
	"clone_max_data_bandwidth":                              "int",
	"clone_max_network_bandwidth":                           "int",
	"clone_ssl_ca":                                          "string",
	"clone_ssl_cert":                                        "string",
	"clone_ssl_key":                                         "string",
	"clone_valid_donor_list":                                "string",
	"collation_connection":                                  "string",
	"collation_database":                                    "string",
	"collation_server":                                      "string",
	"completion_type":                                       "str",
	"concurrent_insert":                                     "str",
	"connect_timeout":                                       "int",
	"connection_control_failed_connections_threshold":       "int",
	"connection_control_max_connection_delay":               "int",
	"connection_control_min_connection_delay":               "int",
	"connection_memory_chunk_size":                          "int",
	"connection_memory_limit":                               "int",
	"cte_max_recursion_depth":                               "int",
	"debug":                                                 "string",
	"debug_sync":                                            "string",
	"default_collation_for_utf8mb4":                         "str",
	"default_password_lifetime":                             "int",
	"default_storage_engine":                                "str",
	"default_table_encryption":                              "bool",
	"default_tmp_storage_engine":                            "str",
	"default_week_format":                                   "int",
	"delay_key_write":                                       "str",
	"delayed_insert_limit":                                  "int",
	"delayed_insert_timeout":                                "int",
	"delayed_queue_size":                                    "int",
	"div_precision_increment":                               "int",
	"dragnet.log_error_filter_rules":                        "string",
	"end_markers_in_json":                                   "bool",
	"enforce_gtid_consistency":                              "str",
	"enterprise_encryption.maximum_rsa_key_size":            "int",
	"enterprise_encryption.rsa_support_legacy_padding":      "bool",
	"eq_range_index_dive_limit":                             "int",
	"event_scheduler":                                       "str",
	"expire_logs_days":                                      "int",
	"explicit_defaults_for_timestamp":                       "bool",
	"flush":                                                 "bool",
	"flush_time":                                            "int",
	"foreign_key_checks":                                    "bool",
	"ft_bool_syntax":                                        "string",
	"general_log":                                           "bool",
	"general_log_file":                                      "string",
	"generated_random_password_length":                      "int",
	"global_connection_memory_limit":                        "int",
	"global_connection_memory_tracking":                     "bool",
	"group_concat_max_len":                                  "int",
	"group_replication_advertise_recovery_endpoints":        "string",
	"group_replication_allow_local_lower_version_join":      "bool",
	"group_replication_auto_increment_increment":            "int",
	"group_replication_autorejoin_tries":                    "int",
	"group_replication_bootstrap_group":                     "bool",
	"group_replication_clone_threshold":                     "int",
	"group_replication_communication_debug_options":         "string",
	"group_replication_communication_max_message_size":      "int",
	"group_replication_components_stop_timeout":             "int",
	"group_replication_compression_threshold":               "int",
	"group_replication_consistency":                         "str",
	"group_replication_enforce_update_everywhere_checks":    "bool",
	"group_replication_exit_state_action":                   "str",
	"group_replication_flow_control_applier_threshold":      "int",
	"group_replication_flow_control_certifier_threshold":    "int",
	"group_replication_flow_control_hold_percent":           "int",
	"group_replication_flow_control_max_commit_quota":       "int",
	"group_replication_flow_control_member_quota_percent":   "int",
	"group_replication_flow_control_min_quota":              "int",
	"group_replication_flow_control_min_recovery_quota":     "int",
	"group_replication_flow_control_mode":                   "str",
	"group_replication_flow_control_period":                 "int",
	"group_replication_flow_control_release_percent":        "int",
	"group_replication_force_members":                       "string",
	"group_replication_group_name":                          "string",
	"group_replication_group_seeds":                         "string",
	"group_replication_gtid_assignment_block_size":          "int",
	"group_replication_ip_allowlist":                        "string",
	"group_replication_ip_whitelist":                        "string",
	"group_replication_local_address":                       "string",
	"group_replication_member_expel_timeout":                "int",
	"group_replication_member_weight":                       "int",
	"group_replication_message_cache_size":                  "int",
	"group_replication_paxos_single_leader":                 "bool",
	"group_replication_poll_spin_loops":                     "int",
	"group_replication_recovery_complete_at":                "str",
	"group_replication_recovery_compression_algorithms":     "Set",
	"group_replication_recovery_get_public_key":             "bool",
	"group_replication_recovery_public_key_path":            "string",
	"group_replication_recovery_reconnect_interval":         "int",
	"group_replication_recovery_retry_count":                "int",
	"group_replication_recovery_ssl_ca":                     "string",
	"group_replication_recovery_ssl_capath":                 "string",
	"group_replication_recovery_ssl_cert":                   "string",
	"group_replication_recovery_ssl_cipher":                 "string",
	"group_replication_recovery_ssl_crl":                    "string",
	"group_replication_recovery_ssl_crlpath":                "string",
	"group_replication_recovery_ssl_key":                    "string",
	"group_replication_recovery_ssl_verify_server_cert":     "bool",
	"group_replication_recovery_tls_ciphersuites":           "string",
	"group_replication_recovery_tls_version":                "string",
	"group_replication_recovery_use_ssl":                    "bool",
	"group_replication_recovery_zstd_compression_level":     "int",
	"group_replication_single_primary_mode":                 "bool",
	"group_replication_ssl_mode":                            "str",
	"group_replication_start_on_boot":                       "bool",
	"group_replication_tls_source":                          "str",
	"group_replication_transaction_size_limit":              "int",
	"group_replication_unreachable_majority_timeout":        "int",
	"group_replication_view_change_uuid":                    "string",
	"gtid_executed_compression_period":                      "int",
	"gtid_mode":                                             "str",
	"gtid_next":                                             "str",
	"gtid_purged":                                           "string",
	"histogram_generation_max_mem_size":                     "int",
	"host_cache_size":                                       "int",
	"identity":                                              "int",
	"immediate_server_version":                              "int",
	"information_schema_stats_expiry":                       "int",
	"init_connect":                                          "string",
	"init_replica":                                          "string",
	"init_slave":                                            "string",
	"innodb_adaptive_flushing":                              "bool",
	"innodb_adaptive_flushing_lwm":                          "int",
	"innodb_adaptive_hash_index":                            "bool",
	"innodb_adaptive_max_sleep_delay":                       "int",
	"innodb_api_bk_commit_interval":                         "int",
	"innodb_api_trx_level":                                  "int",
	"innodb_autoextend_increment":                           "int",
	"innodb_background_drop_list_empty":                     "bool",
	"innodb_buffer_pool_dump_at_shutdown":                   "bool",
	"innodb_buffer_pool_dump_now":                           "bool",
	"innodb_buffer_pool_dump_pct":                           "int",
	"innodb_buffer_pool_filename":                           "string",
	"innodb_buffer_pool_in_core_file":                       "bool",
	"innodb_buffer_pool_load_abort":                         "bool",
	"innodb_buffer_pool_load_now":                           "bool",
	"innodb_buffer_pool_size":                               "int",
	"innodb_change_buffer_max_size":                         "int",
	"innodb_change_buffering":                               "str",
	"innodb_change_buffering_debug":                         "int",
	"innodb_checkpoint_disabled":                            "bool",
	"innodb_checksum_algorithm":                             "str",
	"innodb_cmp_per_index_enabled":                          "bool",
	"innodb_commit_concurrency":                             "int",
	"innodb_compress_debug":                                 "str",
	"innodb_compression_failure_threshold_pct":              "int",
	"innodb_compression_level":                              "int",
	"innodb_compression_pad_pct_max":                        "int",
	"innodb_concurrency_tickets":                            "int",
	"innodb_ddl_buffer_size":                                "int",
	"innodb_ddl_log_crash_reset_debug":                      "bool",
	"innodb_ddl_threads":                                    "int",
	"innodb_deadlock_detect":                                "bool",
	"innodb_default_row_format":                             "str",
	"innodb_disable_sort_file_cache":                        "bool",
	"innodb_doublewrite":                                    "str",
	"innodb_extend_and_initialize":                          "bool",
	"innodb_fast_shutdown":                                  "int",
	"innodb_fil_make_page_dirty_debug":                      "int",
	"innodb_file_per_table":                                 "bool",
	"innodb_fill_factor":                                    "int",
	"innodb_flush_log_at_timeout":                           "int",
	"innodb_flush_log_at_trx_commit":                        "str",
	"innodb_flush_neighbors":                                "str",
	"innodb_flush_sync":                                     "bool",
	"innodb_flushing_avg_loops":                             "int",
	"innodb_fsync_threshold":                                "int",
	"innodb_ft_aux_table":                                   "string",
	"innodb_ft_enable_diag_print":                           "bool",
	"innodb_ft_enable_stopword":                             "bool",
	"innodb_ft_num_word_optimize":                           "int",
	"innodb_ft_result_cache_limit":                          "int",
	"innodb_ft_server_stopword_table":                       "string",
	"innodb_ft_user_stopword_table":                         "string",
	"innodb_idle_flush_pct":                                 "int",
	"innodb_io_capacity":                                    "int",
	"innodb_io_capacity_max":                                "int",
	"innodb_limit_optimistic_insert_debug":                  "int",
	"innodb_lock_wait_timeout":                              "int",
	"innodb_log_buffer_size":                                "int",
	"innodb_log_checkpoint_fuzzy_now":                       "bool",
	"innodb_log_checkpoint_now":                             "bool",
	"innodb_log_checksums":                                  "bool",
	"innodb_log_compressed_pages":                           "bool",
	"innodb_log_spin_cpu_abs_lwm":                           "int",
	"innodb_log_spin_cpu_pct_hwm":                           "int",
	"innodb_log_wait_for_flush_spin_hwm":                    "int",
	"innodb_log_write_ahead_size":                           "int",
	"innodb_log_writer_threads":                             "bool",
	"innodb_lru_scan_depth":                                 "int",
	"innodb_max_dirty_pages_pct":                            "int",
	"innodb_max_dirty_pages_pct_lwm":                        "int",
	"innodb_max_purge_lag":                                  "int",
	"innodb_max_purge_lag_delay":                            "int",
	"innodb_max_undo_log_size":                              "int",
	"innodb_merge_threshold_set_all_debug":                  "int",
	"innodb_monitor_disable":                                "string",
	"innodb_monitor_enable":                                 "string",
	"innodb_monitor_reset":                                  "str",
	"innodb_monitor_reset_all":                              "str",
	"innodb_old_blocks_pct":                                 "int",
	"innodb_old_blocks_time":                                "int",
	"innodb_online_alter_log_max_size":                      "int",
	"innodb_open_files":                                     "int",
	"innodb_optimize_fulltext_only":                         "bool",
	"innodb_parallel_read_threads":                          "int",
	"innodb_print_all_deadlocks":                            "bool",
	"innodb_print_ddl_logs":                                 "bool",
	"innodb_purge_batch_size":                               "int",
	"innodb_purge_rseg_truncate_frequency":                  "int",
	"innodb_random_read_ahead":                              "bool",
	"innodb_read_ahead_threshold":                           "int",
	"innodb_redo_log_archive_dirs":                          "string",
	"innodb_redo_log_capacity":                              "int",
	"innodb_redo_log_encrypt":                               "bool",
	"innodb_replication_delay":                              "int",
	"innodb_rollback_segments":                              "int",
	"innodb_saved_page_number_debug":                        "int",
	"innodb_segment_reserve_factor":                         "int",
	"innodb_spin_wait_delay":                                "int",
	"innodb_spin_wait_pause_multiplier":                     "int",
	"innodb_stats_auto_recalc":                              "bool",
	"innodb_stats_include_delete_marked":                    "bool",
	"innodb_stats_method":                                   "str",
	"innodb_stats_on_metadata":                              "bool",
	"innodb_stats_persistent":                               "bool",
	"innodb_stats_persistent_sample_pages":                  "int",
	"innodb_stats_transient_sample_pages":                   "int",
	"innodb_status_output":                                  "bool",
	"innodb_status_output_locks":                            "bool",
	"innodb_strict_mode":                                    "bool",
	"innodb_sync_spin_loops":                                "int",
	"innodb_table_locks":                                    "bool",
	"innodb_thread_concurrency":                             "int",
	"innodb_thread_sleep_delay":                             "int",
	"innodb_tmpdir":                                         "string",
	"innodb_trx_purge_view_update_only_debug":               "bool",
	"innodb_trx_rseg_n_slots_debug":                         "int",
	"innodb_undo_log_encrypt":                               "bool",
	"innodb_undo_log_truncate":                              "bool",
	"innodb_undo_tablespaces":                               "int",
	"innodb_use_fdatasync":                                  "bool",
	"insert_id":                                             "int",
	"interactive_timeout":                                   "int",
	"internal_tmp_disk_storage_engine":                      "str",
	"internal_tmp_mem_storage_engine":                       "str",
	"join_buffer_size":                                      "int",
	"keep_files_on_create":                                  "bool",
	"key_buffer_size":                                       "int",
	"key_cache_age_threshold":                               "int",
	"key_cache_block_size":                                  "int",
	"key_cache_division_limit":                              "int",
	"keyring_aws_cmk_id":                                    "string",
	"keyring_aws_region":                                    "str",
	"keyring_encrypted_file_data":                           "string",
	"keyring_encrypted_file_password":                       "string",
	"keyring_file_data":                                     "string",
	"keyring_hashicorp_auth_path":                           "string",
	"keyring_hashicorp_ca_path":                             "string",
	"keyring_hashicorp_caching":                             "bool",
	"keyring_hashicorp_role_id":                             "string",
	"keyring_hashicorp_secret_id":                           "string",
	"keyring_hashicorp_server_url":                          "string",
	"keyring_hashicorp_store_path":                          "string",
	"keyring_okv_conf_dir":                                  "string",
	"keyring_operations":                                    "bool",
	"last_insert_id":                                        "int",
	"lc_messages":                                           "string",
	"lc_time_names":                                         "string",
	"local_infile":                                          "bool",
	"lock_wait_timeout":                                     "int",
	"log_bin_trust_function_creators":                       "bool",
	"log_bin_use_v1_row_events":                             "bool",
	"log_error_services":                                    "string",
	"log_error_suppression_list":                            "string",
	"log_error_verbosity":                                   "int",
	"log_output":                                            "Set",
	"log_queries_not_using_indexes":                         "bool",
	"log_raw":                                               "bool",
	"log_slow_admin_statements":                             "bool",
	"log_slow_extra":                                        "bool",
	"log_slow_replica_statements":                           "bool",
	"log_slow_slave_statements":                             "bool",
	"log_statements_unsafe_for_binlog":                      "bool",
	"log_syslog":                                            "bool",
	"log_syslog_facility":                                   "string",
	"log_syslog_include_pid":                                "bool",
	"log_syslog_tag":                                        "string",
	"log_throttle_queries_not_using_indexes":                "int",
	"log_timestamps":                                        "str",
	"long_query_time":                                       "int",
	"low_priority_updates":                                  "bool",
	"mandatory_roles":                                       "string",
	"master_info_repository":                                "string",
	"master_verify_checksum":                                "bool",
	"max_allowed_packet":                                    "int",
	"max_binlog_cache_size":                                 "int",
	"max_binlog_size":                                       "int",
	"max_binlog_stmt_cache_size":                            "int",
	"max_connect_errors":                                    "int",
	"max_connections":                                       "int",
	"max_delayed_threads":                                   "int",
	"max_error_count":                                       "int",
	"max_execution_time":                                    "int",
	"max_heap_table_size":                                   "int",
	"max_insert_delayed_threads":                            "int",
	"max_join_size":                                         "int",
	"max_length_for_sort_data":                              "int",
	"max_points_in_geometry":                                "int",
	"max_prepared_stmt_count":                               "int",
	"max_relay_log_size":                                    "int",
	"max_seeks_for_key":                                     "int",
	"max_sort_length":                                       "int",
	"max_sp_recursion_depth":                                "int",
	"max_user_connections":                                  "int",
	"max_write_lock_count":                                  "int",
	"min_examined_row_limit":                                "int",
	"myisam_data_pointer_size":                              "int",
	"myisam_max_sort_file_size":                             "int",
	"myisam_repair_threads":                                 "int",
	"myisam_sort_buffer_size":                               "int",
	"myisam_stats_method":                                   "str",
	"myisam_use_mmap":                                       "bool",
	"mysql_firewall_mode":                                   "bool",
	"mysql_firewall_trace":                                  "bool",
	"mysql_native_password_proxy_users":                     "bool",
	"mysqlx_compression_algorithms":                         "Set",
	"mysqlx_connect_timeout":                                "int",
	"mysqlx_deflate_default_compression_level":              "int",
	"mysqlx_deflate_max_client_compression_level":           "int",
	"mysqlx_document_id_unique_prefix":                      "int",
	"mysqlx_enable_hello_notice":                            "bool",
	"mysqlx_idle_worker_thread_timeout":                     "int",
	"mysqlx_interactive_timeout":                            "int",
	"mysqlx_lz4_default_compression_level":                  "int",
	"mysqlx_lz4_max_client_compression_level":               "int",
	"mysqlx_max_allowed_packet":                             "int",
	"mysqlx_max_connections":                                "int",
	"mysqlx_min_worker_threads":                             "int",
	"mysqlx_read_timeout":                                   "int",
	"mysqlx_wait_timeout":                                   "int",
	"mysqlx_write_timeout":                                  "int",
	"mysqlx_zstd_default_compression_level":                 "int",
	"mysqlx_zstd_max_client_compression_level":              "int",
	"ndb_allow_copying_alter_table":                         "bool",
	"ndb_autoincrement_prefetch_sz":                         "int",
	"ndb_blob_read_batch_bytes":                             "int",
	"ndb_blob_write_batch_bytes":                            "int",
	"ndb_cache_check_time":                                  "int",
	"ndb_clear_apply_status":                                "bool",
	"ndb_conflict_role":                                     "str",
	"ndb_data_node_neighbour":                               "int",
	"ndb_dbg_check_shares":                                  "int",
	"ndb_default_column_format":                             "str",
	"ndb_deferred_constraints":                              "int",
	"ndb_distribution":                                      "str",
	"ndb_eventbuffer_free_percent":                          "int",
	"ndb_eventbuffer_max_alloc":                             "int",
	"ndb_extra_logging":                                     "int",
	"ndb_force_send":                                        "bool",
	"ndb_fully_replicated":                                  "bool",
	"ndb_index_stat_enable":                                 "bool",
	"ndb_index_stat_option":                                 "string",
	"ndb_join_pushdown":                                     "bool",
	"ndb_log_binlog_index":                                  "bool",
	"ndb_log_empty_epochs":                                  "bool",
	"ndb_log_empty_update":                                  "bool",
	"ndb_log_exclusive_reads":                               "bool",
	"ndb_log_transaction_compression":                       "bool",
	"ndb_log_transaction_compression_level_zstd":            "int",
	"ndb_log_update_as_write":                               "bool",
	"ndb_log_update_minimal":                                "bool",
	"ndb_log_updated_only":                                  "bool",
	"ndb_metadata_check":                                    "bool",
	"ndb_metadata_check_interval":                           "int",
	"ndb_metadata_sync":                                     "bool",
	"ndb_optimization_delay":                                "int",
	"ndb_read_backup":                                       "bool",
	"ndb_recv_thread_activation_threshold":                  "int",
	"ndb_recv_thread_cpu_mask":                              "Bitmap",
	"ndb_replica_batch_size":                                "int",
	"ndb_replica_blob_write_batch_bytes":                    "int",
	"ndb_report_thresh_binlog_epoch_slip":                   "int",
	"ndb_report_thresh_binlog_mem_usage":                    "int",
	"ndb_row_checksum":                                      "int",
	"ndb_schema_dist_lock_wait_timeout":                     "int",
	"ndb_show_foreign_key_mock_tables":                      "bool",
	"ndb_slave_conflict_role":                               "str",
	"ndb_table_no_logging":                                  "bool",
	"ndb_table_temporary":                                   "bool",
	"ndb_use_exact_count":                                   "bool",
	"ndb_use_transactions":                                  "bool",
	"ndbinfo_max_bytes":                                     "int",
	"ndbinfo_max_rows":                                      "int",
	"ndbinfo_offline":                                       "bool",
	"ndbinfo_show_hidden":                                   "bool",
	"net_buffer_length":                                     "int",
	"net_read_timeout":                                      "int",
	"net_retry_count":                                       "int",
	"net_write_timeout":                                     "int",
	"new":                                                   "bool",
	"offline_mode":                                          "bool",
	"old_alter_table":                                       "bool",
	"optimizer_prune_level":                                 "int",
	"optimizer_search_depth":                                "int",
	"optimizer_switch":                                      "Set",
	"optimizer_trace":                                       "string",
	"optimizer_trace_features":                              "string",
	"optimizer_trace_limit":                                 "int",
	"optimizer_trace_max_mem_size":                          "int",
	"optimizer_trace_offset":                                "int",
	"original_commit_timestamp":                             "int",
	"original_server_version":                               "int",
	"parser_max_mem_size":                                   "int",
	"partial_revokes":                                       "bool",
	"password_history":                                      "int",
	"password_require_current":                              "bool",
	"password_reuse_interval":                               "int",
	"performance_schema_max_digest_sample_age":              "int",
	"performance_schema_show_processlist":                   "bool",
	"preload_buffer_size":                                   "int",
	"print_identified_with_as_hex":                          "bool",
	"profiling":                                             "bool",
	"profiling_history_size":                                "int",
	"protocol_compression_algorithms":                       "Set",
	"pseudo_replica_mode":                                   "bool",
	"pseudo_slave_mode":                                     "bool",
	"pseudo_thread_id":                                      "int",
	"query_alloc_block_size":                                "int",
	"query_prealloc_size":                                   "int",
	"rand_seed1":                                            "int",
	"rand_seed2":                                            "int",
	"range_alloc_block_size":                                "int",
	"range_optimizer_max_mem_size":                          "int",
	"rbr_exec_mode":                                         "str",
	"read_buffer_size":                                      "int",
	"read_only":                                             "bool",
	"read_rnd_buffer_size":                                  "int",
	"regexp_stack_limit":                                    "int",
	"regexp_time_limit":                                     "int",
	"relay_log_info_repository":                             "string",
	"relay_log_purge":                                       "bool",
	"replica_allow_batching":                                "bool",
	"replica_checkpoint_group":                              "int",
	"replica_checkpoint_period":                             "int",
	"replica_compressed_protocol":                           "bool",
	"replica_exec_mode":                                     "str",
	"replica_max_allowed_packet":                            "int",
	"replica_net_timeout":                                   "int",
	"replica_parallel_type":                                 "str",
	"replica_parallel_workers":                              "int",
	"replica_pending_jobs_size_max":                         "int",
	"replica_preserve_commit_order":                         "bool",
	"replica_sql_verify_checksum":                           "bool",
	"replica_transaction_retries":                           "int",
	"replica_type_conversions":                              "Set",
	"replication_optimize_for_static_plugin_config":         "bool",
	"replication_sender_observe_commit_only":                "bool",
	"require_row_format":                                    "bool",
	"require_secure_transport":                              "bool",
	"resultset_metadata":                                    "str",
	"rewriter_enabled":                                      "bool",
	"rewriter_enabled_for_threads_without_privilege_checks": "bool",
	"rewriter_verbose":                                      "int",
	"rpl_read_size":                                         "int",
	"rpl_semi_sync_master_enabled":                          "bool",
	"rpl_semi_sync_master_timeout":                          "int",
	"rpl_semi_sync_master_trace_level":                      "int",
	"rpl_semi_sync_master_wait_for_slave_count":             "int",
	"rpl_semi_sync_master_wait_no_slave":                    "bool",
	"rpl_semi_sync_master_wait_point":                       "str",
	"rpl_semi_sync_replica_enabled":                         "bool",
	"rpl_semi_sync_replica_trace_level":                     "int",
	"rpl_semi_sync_slave_enabled":                           "bool",
	"rpl_semi_sync_slave_trace_level":                       "int",
	"rpl_semi_sync_source_enabled":                          "bool",
	"rpl_semi_sync_source_timeout":                          "int",
	"rpl_semi_sync_source_trace_level":                      "int",
	"rpl_semi_sync_source_wait_for_replica_count":           "int",
	"rpl_semi_sync_source_wait_no_replica":                  "bool",
	"rpl_semi_sync_source_wait_point":                       "str",
	"rpl_stop_replica_timeout":                              "int",
	"rpl_stop_slave_timeout":                                "int",
	"schema_definition_cache":                               "int",
	"secondary_engine_cost_threshold":                       "int",
	"select_into_buffer_size":                               "int",
	"select_into_disk_sync":                                 "bool",
	"select_into_disk_sync_delay":                           "int",
	"server_id":                                             "int",
	"session_track_gtids":                                   "str",
	"session_track_schema":                                  "bool",
	"session_track_state_change":                            "bool",
	"session_track_system_variables":                        "string",
	"session_track_transaction_info":                        "str",
	"sha256_password_proxy_users":                           "bool",
	"show_create_table_skip_secondary_engine":               "bool",
	"show_create_table_verbosity":                           "bool",
	"show_gipk_in_create_table_and_information_schema":      "bool",
	"show_old_temporals":                                    "bool",
	"slave_allow_batching":                                  "bool",
	"slave_checkpoint_group":                                "int",
	"slave_checkpoint_period":                               "int",
	"slave_compressed_protocol":                             "bool",
	"slave_exec_mode":                                       "str",
	"slave_max_allowed_packet":                              "int",
	"slave_net_timeout":                                     "int",
	"slave_parallel_type":                                   "str",
	"slave_parallel_workers":                                "int",
	"slave_pending_jobs_size_max":                           "int",
	"slave_preserve_commit_order":                           "bool",
	"slave_rows_search_algorithms":                          "Set",
	"slave_sql_verify_checksum":                             "bool",
	"slave_transaction_retries":                             "int",
	"slave_type_conversions":                                "Set",
	"slow_launch_time":                                      "int",
	"slow_query_log":                                        "bool",
	"slow_query_log_file":                                   "string",
	"sort_buffer_size":                                      "int",
	"source_verify_checksum":                                "bool",
	"sql_auto_is_null":                                      "bool",
	"sql_big_selects":                                       "bool",
	"sql_buffer_result":                                     "bool",
	"sql_generate_invisible_primary_key":                    "bool",
	"sql_log_bin":                                           "bool",
	"sql_log_off":                                           "bool",
	"sql_mode":                                              "Set",
	"sql_notes":                                             "bool",
	"sql_quote_show_create":                                 "bool",
	"sql_replica_skip_counter":                              "int",
	"sql_require_primary_key":                               "bool",
	"sql_safe_updates":                                      "bool",
	"sql_select_limit":                                      "int",
	"sql_slave_skip_counter":                                "int",
	"sql_warnings":                                          "bool",
	"ssl_ca":                                                "string",
	"ssl_capath":                                            "string",
	"ssl_cert":                                              "string",
	"ssl_cipher":                                            "string",
	"ssl_crl":                                               "string",
	"ssl_crlpath":                                           "string",
	"ssl_fips_mode":                                         "str",
	"ssl_key":                                               "string",
	"ssl_session_cache_mode":                                "bool",
	"ssl_session_cache_timeout":                             "int",
	"stored_program_cache":                                  "int",
	"stored_program_definition_cache":                       "int",
	"super_read_only":                                       "bool",
	"sync_binlog":                                           "int",
	"sync_master_info":                                      "int",
	"sync_relay_log":                                        "int",
	"sync_relay_log_info":                                   "int",
	"sync_source_info":                                      "int",
	"syseventlog.facility":                                  "string",
	"syseventlog.include_pid":                               "bool",
	"syseventlog.tag":                                       "string",
	"table_definition_cache":                                "int",
	"table_encryption_privilege_check":                      "bool",
	"table_open_cache":                                      "int",
	"tablespace_definition_cache":                           "int",
	"temptable_max_mmap":                                    "int",
	"temptable_max_ram":                                     "int",
	"temptable_use_mmap":                                    "bool",
	"terminology_use_previous":                              "str",
	"thread_cache_size":                                     "int",
	"thread_pool_high_priority_connection":                  "int",
	"thread_pool_max_active_query_threads":                  "int",
	"thread_pool_max_transactions_limit":                    "int",
	"thread_pool_max_unused_threads":                        "int",
	"thread_pool_prio_kickup_timer":                         "int",
	"thread_pool_query_threads_per_group":                   "int",
	"thread_pool_stall_limit":                               "int",
	"thread_pool_transaction_delay":                         "int",
	"time_zone":                                             "string",
	"timestamp":                                             "int",
	"tls_ciphersuites":                                      "string",
	"tls_version":                                           "string",
	"tmp_table_size":                                        "int",
	"transaction_alloc_block_size":                          "int",
	"transaction_allow_batching":                            "bool",
	"transaction_isolation":                                 "str",
	"transaction_prealloc_size":                             "int",
	"transaction_read_only":                                 "bool",
	"transaction_write_set_extraction":                      "str",
	"unique_checks":                                         "bool",
	"updatable_views_with_limit":                            "bool",
	"use_secondary_engine":                                  "str",
	"validate_password_check_user_name":                     "bool",
	"validate_password_dictionary_file":                     "string",
	"validate_password_length":                              "int",
	"validate_password_mixed_case_count":                    "int",
	"validate_password_number_count":                        "int",
	"validate_password_policy":                              "str",
	"validate_password_special_char_count":                  "int",
	"validate_password.check_user_name":                     "bool",
	"validate_password.dictionary_file":                     "string",
	"validate_password.length":                              "int",
	"validate_password.mixed_case_count":                    "int",
	"validate_password.number_count":                        "int",
	"validate_password.policy":                              "str",
	"validate_password.special_char_count":                  "int",
	"version_tokens_session":                                "string",
	"wait_timeout":                                          "int",
	"windowing_use_high_precision":                          "bool",
	"xa_detach_on_prepare":                                  "bool",
}
